stages:
  - test
  - bench

image: rust:latest

test:
  stage: test
  script:
    - cargo test

bench_run:
  stage: bench
  script:
    - cargo build --release
    - (cargo run --release & PID=$! ; sleep 10 ; kill "$PID") || true
